services:
  rpc:
    image: docker.io/hyperledger/besu:latest
    container_name: opendid-besu-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "9545:9545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - type: bind
        source: ./genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - rpc-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --data-path=/opt/besu/data
      --miner-enabled
      --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73
      --rpc-http-cors-origins=all
      --rpc-http-max-active-connections=10000
      --host-allowlist=*
      --rpc-ws-enabled
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,WEB3,TXPOOL,QBFT,TRACE,DEBUG,ADMIN
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --min-gas-price=0
    networks:
      besu:
        ipv4_address: 172.28.0.2

  validator1:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator1",
               "--bootnodes=enode://${BOOT_NODE_ID}@172.28.0.2:30303",
               "--nat-method=DOCKER",
               "--min-gas-price=0",
               "--p2p-port=30304" ]
    volumes:
      - ./common-config.toml:/opt/besu/common-config.toml:ro
      - ./genesis.json:/opt/besu/genesis.json:ro
      - ./keys/validator1/key:/opt/besu/key:ro
      - validator1-data:/opt/besu/data
    networks:
      besu:
        ipv4_address: 172.28.0.3

  validator2:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator2",
               "--bootnodes=enode://${BOOT_NODE_ID}@172.28.0.2:30303",
               "--nat-method=DOCKER",
               "--min-gas-price=0",
               "--p2p-port=30305" ]
    volumes:
      - ./common-config.toml:/opt/besu/common-config.toml:ro
      - ./genesis.json:/opt/besu/genesis.json:ro
      - ./keys/validator2/key:/opt/besu/key:ro
      - validator2-data:/opt/besu/data
    networks:
      besu:
        ipv4_address: 172.28.0.4

  validator3:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator3",
               "--bootnodes=enode://${BOOT_NODE_ID}@172.28.0.2:30303",
               "--nat-method=DOCKER",
               "--min-gas-price=0",
               "--p2p-port=30306" ]
    volumes:
      - ./common-config.toml:/opt/besu/common-config.toml:ro
      - ./genesis.json:/opt/besu/genesis.json:ro
      - ./keys/validator3/key:/opt/besu/key:ro
      - validator3-data:/opt/besu/data
    networks:
      besu:
        ipv4_address: 172.28.0.5

  validator4:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator4",
               "--bootnodes=enode://${BOOT_NODE_ID}@172.28.0.2:30303",
               "--nat-method=DOCKER",
               "--min-gas-price=0",
               "--p2p-port=30307" ]
    volumes:
      - ./common-config.toml:/opt/besu/common-config.toml:ro
      - ./genesis.json:/opt/besu/genesis.json:ro
      - ./keys/validator4/key:/opt/besu/key:ro
      - validator4-data:/opt/besu/data
    networks:
      besu:

  validator5:
    image: hyperledger/besu:latest
    command: [ "--config-file=/opt/besu/common-config.toml",
               "--identity=validator5",
               "--bootnodes=enode://${BOOT_NODE_ID}@172.28.0.2:30303",
               "--nat-method=DOCKER",
               "--min-gas-price=0",
               "--p2p-port=30308" ]
    volumes:
      - ./common-config.toml:/opt/besu/common-config.toml:ro
      - ./genesis.json:/opt/besu/genesis.json:ro
      - ./keys/validator5/key:/opt/besu/key:ro
      - validator5-data:/opt/besu/data
    networks:
      besu:
        ipv4_address: 172.28.0.6

networks:
  besu:
    name: besu
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  rpc-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${RPC_DATA_PATH}
  validator1-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${VALIDATOR1_DATA_PATH}
  validator2-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${VALIDATOR2_DATA_PATH}
  validator3-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${VALIDATOR3_DATA_PATH}
  validator4-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${VALIDATOR4_DATA_PATH}
  validator5-data:
    driver_opts:
      type: "local"
      o: "bind,nolock,soft,rw,uid=1000,gid=1000"
      device: $PWD/${VALIDATOR5_DATA_PATH}