services:
  besu:
    image: docker.io/hyperledger/besu:latest
    container_name: opendid-besu-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "9545:9545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - type: bind
        source: ./genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - besu_opendid_data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --data-path=/opt/besu/data
      --miner-enabled
      --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73
      --rpc-http-cors-origins=all
      --rpc-http-max-active-connections=10000
      --host-allowlist=*
      --rpc-ws-enabled
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,WEB3,TXPOOL,QBFT,TRACE,DEBUG
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --min-gas-price=0
    networks:
      - besu

volumes:
  besu_opendid_data:

networks:
  besu:
    name: besu
    driver: bridge